/*
 * Gen Matrix Test Bench - SOFTWARE VERSION
 * Tests Kyber matrix generation (gen_a and gen_at) with cycle counting
 * Compares against golden reference values
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "fips202.h"
#include "kyber_params.h"


#include "core_v_mini_mcu.h"
#include "csr.h"

/* Forward declarations */
extern void gen_matrix(polyvec *a, const uint8_t seed[KYBER_SYMBYTES], int transposed);
extern void gen_a(polyvec *a, const uint8_t seed[KYBER_SYMBYTES]);
extern void gen_at(polyvec *a, const uint8_t seed[KYBER_SYMBYTES]);

/* Test result tracking */
static int total_tests = 0;
static int passed_tests = 0;

/* Performance counters */
typedef struct {
    uint32_t cycles;
    uint32_t instructions;
} perf_counters_t;

/*
 * Helper: Read performance counters
 */
static void read_perf_counters(perf_counters_t *perf)
{
    CSR_READ(CSR_REG_MCYCLE, &perf->cycles);
    CSR_READ(CSR_REG_MINSTRET, &perf->instructions);
}

/*
 * Helper: Reset performance counters
 */
static void reset_perf_counters(void)
{
    CSR_WRITE(CSR_REG_MCYCLE, 0);
    CSR_WRITE(CSR_REG_MINSTRET, 0);
}

/*
 * Helper: Compare two matrix arrays (each with KYBER_K polyvecs)
 */
static int compare_polyvec(const polyvec *a, const polyvec *b)
{
    /* Compare all KYBER_K polyvecs in the matrix */
    for(int k = 0; k < KYBER_K; k++) {
        for(int i = 0; i < KYBER_K; i++) {
            for(int j = 0; j < KYBER_N; j++) {
                if(a[k].vec[i].coeffs[j] != b[k].vec[i].coeffs[j]) {
                    return 0;  /* Mismatch */
                }
            }
        }
    }
    return 1;  /* Match */
}

/*
 * Helper: Print polynomial vector (first few coefficients)
 */
static void print_polyvec_sample(const polyvec *a, int count)
{
    printf("  First %d coefficients of a[0][0]: ", count);
    for(int i = 0; i < count && i < KYBER_N; i++) {
        printf("%d ", a[0].vec[0].coeffs[i]);
    }
    printf("\n");
    printf("  First %d coefficients of a[0][1]: ", count);
    for(int i = 0; i < count && i < KYBER_N; i++) {
        printf("%d ", a[0].vec[1].coeffs[i]);
    }
    printf("\n");
    printf("  First %d coefficients of a[1][0]: ", count);
    for(int i = 0; i < count && i < KYBER_N; i++) {
        printf("%d ", a[1].vec[0].coeffs[i]);
    }
    printf("\n");
    printf("  First %d coefficients of a[1][1]: ", count);
    for(int i = 0; i < count && i < KYBER_N; i++) {
        printf("%d ", a[1].vec[1].coeffs[i]);
    }
    printf("\n");
}

/*
 * Fixed test seed: standard NIST test vector pattern
 * This represents a public seed used in key generation
 */
static const uint8_t TEST_SEED[KYBER_SYMBYTES] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f
};

/*
 * Golden reference values for TEST_SEED
 * Generated by running reference Kyber implementation with TEST_SEED
 * and capturing first 4 coefficients of each polynomial
 */
typedef struct {
    int16_t a00_first4[4];  /* a[0][0] first 4 coefficients */
    int16_t a01_first4[4];  /* a[0][1] first 4 coefficients */
    int16_t a10_first4[4];  /* a[1][0] first 4 coefficients */
    int16_t a11_first4[4];  /* a[1][1] first 4 coefficients */
} golden_matrix_t;

/* Golden reference for gen_a (transposed=0) */
static const golden_matrix_t GOLDEN_GEN_A = {
    .a00_first4 = {1364, 199, 712, 506},
    .a01_first4 = {483, 1189, 1089, 2233},
    .a10_first4 = {536, 843, 1994, 2664},
    .a11_first4 = {314, 1867, 3116, 2581}
};

/* Golden reference for gen_at (transposed=1) */
static const golden_matrix_t GOLDEN_GEN_AT = {
    .a00_first4 = {1364, 199, 712, 506},
    .a01_first4 = {536, 843, 1994, 2664},
    .a10_first4 = {483, 1189, 1089, 2233},
    .a11_first4 = {314, 1867, 3116, 2581}
};

/*
 * Helper: Verify polynomial vector against golden reference
 */
static int verify_polyvec_golden(const polyvec *a, const golden_matrix_t *golden)
{
    /* Check a[0][0] = a[0].vec[0] */
    for(int i = 0; i < 4; i++) {
        if(a[0].vec[0].coeffs[i] != golden->a00_first4[i])
            return 0;
    }
    /* Check a[0][1] = a[0].vec[1] */
    for(int i = 0; i < 4; i++) {
        if(a[0].vec[1].coeffs[i] != golden->a01_first4[i])
            return 0;
    }
    /* Check a[1][0] = a[1].vec[0] */
    for(int i = 0; i < 4; i++) {
        if(a[1].vec[0].coeffs[i] != golden->a10_first4[i])
            return 0;
    }
    /* Check a[1][1] = a[1].vec[1] */
    for(int i = 0; i < 4; i++) {
        if(a[1].vec[1].coeffs[i] != golden->a11_first4[i])
            return 0;
    }
    return 1;
}

/*
 * TEST 1: gen_a basic functionality
 */
void test_gen_a_basic(void)
{
    polyvec a[KYBER_K];
    perf_counters_t perf_start, perf_end;

    reset_perf_counters();
    read_perf_counters(&perf_start);
    gen_a(a, TEST_SEED);
    read_perf_counters(&perf_end);

    uint32_t cycles = perf_end.cycles - perf_start.cycles;

    total_tests++;
    if(verify_polyvec_golden(a, &GOLDEN_GEN_A)) {
        passed_tests++;
        printf("Test 1: gen_a - PASS (Cycles: %u)\n", cycles);
    } else {
        printf("Test 1: gen_a - FAIL (Cycles: %u)\n", cycles);
        printf("  Got:      ");
        for(int i = 0; i < 4; i++) printf("%d ", a[0].vec[0].coeffs[i]);
        printf("\n  Expected: 1364 199 712 506\n");
    }
}

/*
 * TEST 2: gen_at basic functionality
 */
void test_gen_at_basic(void)
{
    polyvec at[KYBER_K];
    perf_counters_t perf_start, perf_end;

    reset_perf_counters();
    read_perf_counters(&perf_start);
    gen_at(at, TEST_SEED);
    read_perf_counters(&perf_end);

    uint32_t cycles = perf_end.cycles - perf_start.cycles;

    total_tests++;
    if(verify_polyvec_golden(at, &GOLDEN_GEN_AT)) {
        passed_tests++;
        printf("Test 2: gen_at - PASS (Cycles: %u)\n", cycles);
    } else {
        printf("Test 2: gen_at - FAIL (Cycles: %u)\n", cycles);
        printf("  Got:      ");
        for(int i = 0; i < 4; i++) printf("%d ", at[0].vec[0].coeffs[i]);
        printf("\n  Expected: 1364 199 712 506\n");
    }
}

/*
 * TEST 3: Transposition correctness
 * Verify that gen_at(seed) == transpose(gen_a(seed))
 */
void test_transposition_property(void)
{
    polyvec a[KYBER_K], at[KYBER_K];

    gen_a(a, TEST_SEED);
    gen_at(at, TEST_SEED);

    /* Check transposition property: at[i][j] should contain same value as a[j][i] */
    int correct = 1;
    for(int i = 0; i < KYBER_K && correct; i++) {
        for(int j = 0; j < KYBER_K && correct; j++) {
            if(at[i].vec[j].coeffs[0] != a[j].vec[i].coeffs[0]) {
                correct = 0;
            }
        }
    }

    total_tests++;
    if(correct) {
        passed_tests++;
        printf("Test 3: Transposition - PASS\n");
    } else {
        printf("Test 3: Transposition - FAIL\n");
    }
}

/*
 * TEST 4: Deterministic seeding
 * Same seed must produce same output
 */
void test_deterministic_seeding(void)
{
    polyvec a1[KYBER_K], a2[KYBER_K];

    gen_a(a1, TEST_SEED);
    gen_a(a2, TEST_SEED);

    total_tests++;
    if(compare_polyvec(a1, a2)) {
        passed_tests++;
        printf("Test 4: Deterministic - PASS\n");
    } else {
        printf("Test 4: Deterministic - FAIL\n");
    }
}

/*
 * TEST 5: Different seeds produce different matrices
 */
void test_different_seeds(void)
{
    polyvec a1[KYBER_K], a2[KYBER_K];
    uint8_t seed2[KYBER_SYMBYTES];

    memcpy(seed2, TEST_SEED, KYBER_SYMBYTES);
    seed2[0] ^= 0xFF;

    gen_a(a1, TEST_SEED);
    gen_a(a2, seed2);

    total_tests++;
    if(!compare_polyvec(a1, a2)) {
        passed_tests++;
        printf("Test 5: Different Seeds - PASS\n");
    } else {
        printf("Test 5: Different Seeds - FAIL\n");
    }
}

/*
 * Main test runner
 */
int main(void)
{
    CSR_CLEAR_BITS(CSR_REG_MCOUNTINHIBIT, 0x1);
    test_gen_a_basic();
    test_gen_at_basic();
    test_transposition_property();
    test_deterministic_seeding();
    test_different_seeds();

    printf("\n%d/%d tests passed\n", passed_tests, total_tests);

    return (passed_tests == total_tests) ? 0 : 1;
}

// Test 1: gen_a - PASS (Cycles: 411760)
// Test 2: gen_at - PASS (Cycles: 411744)
// Test 3: Transposition - PASS
// Test 4: Deterministic - PASS
// Test 5: Different Seeds - PASS

//Test 1: gen_a (HW) - PASS (Cycles: 66860)
//Test 2: gen_at (HW) - PASS (Cycles: 66844)
//Test 3: Multi-block XOF - PASS (Run1: 66858, Run2: 66858)
//Test 4: Rejection sampling - PASS (Cycles/coeff: )
//Test 5: Deterministic (HW) - PASS


//Test 1: gen_a (HW) - PASS (Cycles: 24599)
//Test 2: gen_at (HW) - PASS (Cycles: 24579)
//Test 3: Multi-block XOF - PASS (Run1: 24597, Run2: 24597)
//Test 4: Rejection sampling - PASS (Cycles/coeff: )
//Test 5: Deterministic (HW) - PASS